# Generated by Django 5.2.17 on 2026-09-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('referencia', models.CharField(blank=True, max_length=300, verbose_name='Ponto de referência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='CNH')),
                ('categoria_cnh', models.CharField(default='D', max_length=5, verbose_name='Categoria CNH')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='contas.perfil', verbose_name='Perfil')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas', to='transporte.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['perfil__usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('tempo_estimado', models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True, verbose_name='Tempo estimado desde a parada anterior')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Parada da Rota',
                'verbose_name_plural': 'Paradas da Rota',
                'ordering': ['rota', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='transporte.operador', verbose_name='Operador')),
                ('paradas', models.ManyToManyField(related_name='rotas', through='transporte.ParadaRota', to='transporte.parada', verbose_name='Paradas')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='paradarota',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_ordenadas', to='transporte.rota', verbose_name='Rota'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('van', 'Van'), ('micro_onibus', 'Micro-ônibus'), ('lotacao', 'Lotação'), ('onibus', 'Ônibus')], default='van', max_length=20, verbose_name='Tipo')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade (passageiros)')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='transporte.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data/hora de saída')),
                ('data_hora_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de chegada')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20, verbose_name='Status')),
                ('vagas_disponiveis', models.PositiveIntegerField(verbose_name='Vagas disponíveis')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='transporte.motorista', verbose_name='Motorista')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='transporte.rota', verbose_name='Rota')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='transporte.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_hora_saida'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='paradarota',
            unique_together={('rota', 'ordem'), ('rota', 'parada')},
        ),
    ]
