# Generated by Django 5.2.17 on 2026-09-27 19:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota (1-5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='transporte.viagem', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criada_em'],
                'unique_together': {('viagem', 'passageiro')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('utilizada', 'Utilizada')], default='confirmada', max_length=20, verbose_name='Status')),
                ('quantidade_vagas', models.PositiveIntegerField(default=1, verbose_name='Quantidade de vagas')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da reserva')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do cancelamento')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='transporte.viagem', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
                'unique_together': {('viagem', 'passageiro')},
            },
        ),
    ]
